[[polymake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03fab98b549e32a3a93bf4f30878768f6b5d0bf2"
os = "macos"

    [[polymake.download]]
    sha256 = "32984a517bb2038e9863630119e1cd37403ffe663a9d14b50ad851759146bb52"
    url = "https://github.com/benlorenz/polymake_jll.jl/releases/download/polymake-v4.1.2+0/polymake.v4.1.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[polymake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da7379c75261d15fd4ecae5f9e0f75bc34edc0d1"
libc = "glibc"
os = "linux"

    [[polymake.download]]
    sha256 = "12da43abebc0ec8c606ef97215dde635798229e2bc785194b5a90be9b551e87f"
    url = "https://github.com/benlorenz/polymake_jll.jl/releases/download/polymake-v4.1.2+0/polymake.v4.1.2.x86_64-linux-gnu-cxx11.tar.gz"
