[[polymake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "749caa0c180e8b6404e03106a379e836cae4992d"
os = "macos"

    [[polymake.download]]
    sha256 = "6409b85e07ca22bdc40b9da28794c48bdd14dd20420b323775f0d87a4368b6f3"
    url = "https://github.com/benlorenz/polymake_jll.jl/releases/download/polymake-v4.1.3+0/polymake.v4.1.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[polymake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3a46c6a8b8160a2af71953b6100b52d9fa20b7c"
libc = "glibc"
os = "linux"

    [[polymake.download]]
    sha256 = "0709258093ac7b9e4897cd393ccd72994ec5d1862a3290bea7db3963c9f3295b"
    url = "https://github.com/benlorenz/polymake_jll.jl/releases/download/polymake-v4.1.3+0/polymake.v4.1.3.x86_64-linux-gnu-cxx11.tar.gz"
